#ifndef TCOMMONTYPES_H
#define TCOMMONTYPES_H
#include <stdio.h>
#include <QtCore/QtGlobal>

namespace YR2K {
    enum TEPanelIndex
    {
        PANEL_INVALID                   = -1,
        PANEL_WELCOME                   = 0,
        PANEL_ASSET_SETUP,
        PANEL_ADMIN_SETUP,
        PANEL_MACHINE_GROUP_FUNC_BASE_SETUP,
        PANEL_MACHINE_GROUP_FUNC_DETAIL_SETUP,
        PANEL_MACHINE_GROUP_REPORT_ENTERAINTMENT,
        PANEL_MACHINE_GROUP_REPORT_GIFT,
        PANEL_MACHINE_GROUP_REPORT_LOTTERY,
        PANEL_INVENTORY_REPORT,
        PANEL_MACHINE_GROUP_DIFFERENCE,
        PANEL_WARNING_SYSTEM,

        PANEL_NUM
    };

    enum TECategory
    {
        CATEGORY_INVALID = -1,
        CATEGORY_CABINET = 0,
        CATEGORY_LOTTERY,
        CATEGORY_SIMULATE,
        CATEGORY_COINDOZER,
        CATEGORY_WAGER,

        CATEGORY_NUM
    };

    enum TESTatementType
    {
        STATEMENT_INVALID = -1,
        STATEMENT_TYPE_1 = 0,
        STATEMENT_TYPE_2,
        STATEMENT_TYPE_3,

        STATEMENT_NUM
    };

    enum TEAssetSetupTableColumnIndex
    {
        ASSET_SETUP_TABLE_COLUMN_INVALID = -1,
        ASSET_SETUP_TABLE_COLUMN_CATEGORY_NAME = 0,
        ASSET_SETUP_TABLE_COLUMN_CLEARCOIN_PERIOD,
        ASSET_SETUP_TABLE_COLUMN_CLEARCOIN_MARGIN,
        ASSET_SETUP_TABLE_COLUMN_LIABILITIES,
        ASSET_SETUP_TABLE_COLUMN_ALLOWLOSSDAYS,
        ASSET_SETUP_TABLE_COLUMN_STATEMENTTYPE,

        ASSET_SETUP_TABLE_COLUMN_NUM
    };

    enum TEMachineBaseSetupColumnIndex
    {
        BASE_SETUP_TABLE_COLUMN_INVALID = -1,
        BASE_SETUP_TABLE_COLUMN_FACTORY_NAME = 0,
        BASE_SETUP_TABLE_COLUMN_FACTORY_PHONE_NUMBER,
        BASE_SETUP_TABLE_COLUMN_LOCATION,
        BASE_SETUP_TABLE_COLUMN_BUSINESS_CONDITIONS,
        BASE_SETUP_TABLE_COLUMN_REMARK,

        BASE_SETUP_TABLE_COLUMN_NUM
    };

    enum TEMachineFuncDetailSetupColumnIndex
    {
        DETAIL_SETUP_TABLE_COLUMN_INVALID = -1,
        DETAIL_SETUP_TABLE_COLUMN_ASSET_TYPE = 0,
        DETAIL_SETUP_TABLE_COLUMN_MACHINE_TYPE,
        DETAIL_SETUP_TABLE_COLUMN_CASH_RATIO,
        DETAIL_SETUP_TABLE_COLUMN_COIN_RATIO,
        DETAIL_SETUP_TABLE_COLUMN_MAIN_PROBABILITY,
        DETAIL_SETUP_TABLE_COLUMN_PROBABILITY_RANGE,
        DETAIL_SETUP_TABLE_COLUMN_MAX_POINTS,
        DETAIL_SETUP_TABLE_COLUMN_MIN_POINTS,
        DETAIL_SETUP_TABLE_COLUMN_MARK_POINTS,
        DETAIL_SETUP_TABLE_COLUMN_DRAW_POINTS,
        DETAIL_SETUP_TABLE_COLUMN_PUSH_POINT_DAYS,
        DETAIL_SETUP_TABLE_COLUMN_CLEAR_POINT_CYCLE,

        DETAIL_SETUP_TABLE_COLUMN_NUM
    };

    enum TEStatementCategory
    {
        STATMENT_CATEGORY_ENTERTAINMENT = 0,
        STATMENT_CATEGORY_GIFT,
        STATMENT_CATEGORY_GAMING,
        STATMENT_CATEGORY_NUM,
    };

}
#endif  // TCOMMONTYPES_H

